apiVersion: v1
kind: Pod
metadata:
  name: annotations-nginx-yaml
  annotations:
    supportcall: 1800-234-3434
    costcode: RRTEYEY
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80
          name: http