apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: phpcolorapp
  labels:
    color: blue
    version: "1"
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      color: blue      
  template:
    metadata:
      labels:
        color: blue
    spec:
      containers:
      - name: phpallcolor-blue
        image: "muthu4all/php_app_color:blue"