apiVersion: v1
kind: Pod
metadata:
  name: nginx-yaml
spec:
  nodeName: node4
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80
          name: http