apiVersion: apps/v1
kind: Deployment
metadata:
  name: selfrepel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selfrepel
  template:
    metadata:
      labels:
        app: selfrepel
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector: 
              matchExpressions:  
              - key: app
                operator: In
                values:
                - selfrepel
      containers:
      - name: nginx
        image: nginx
        ports:
       - containerPort: 80