 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: withtoleration-nginx-deployment
   labels:
     app: nginx
 spec:
   replicas: 4
   selector:
     matchLabels:
       app: nginx
   template:
     metadata:
       labels:
         app: nginx
     spec:
       tolerations:
       - key: "CostCode"
         operator: "Equal"
         value: "CC1"
         effect: "NoSchedule"
       containers:
       - name: nginx
         image: nginx:latest
         ports:
         - containerPort: 80